# Generated by Django 5.1.5 on 2025-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('task_func', models.CharField(choices=[('Testowa analiza - nie robi nic i nie spełnia sygnatury analizy', 'test_task'), ('Analiza rzutów rożnych 1', 'analyse_corners_line_auto'), ('Korelacja posiadania piłki do wyniku meczu', 'correlation_bp2result'), ('Szukanie korelacji pomiędzy statystykami', 'oblicz_korelacje_statystyk_kazdy_z_kazdym')], max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
