# Generated by Django 5.1.5 on 2025-01-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='description',
        ),
    ]
