# Generated by Django 5.1.5 on 2025-01-30 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('task_func', models.CharField(choices=[('test_add_analysis_choices', 'Test dodawania analizy'), ('test_task', 'Testowa analiza'), ('analyse_corners_line_auto', 'Analiza rzutów rożnych 1'), ('correlation_bp2result', 'Korelacja posiadania piłki do wyniku meczu'), ('oblicz_korelacje_statystyk_kazdy_z_kazdym', 'Szukanie korelacji pomiędzy statystykami')], max_length=128, verbose_name='Name')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'analyses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_name', models.CharField(max_length=128)),
                ('result', models.JSONField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.order')),
            ],
        ),
    ]
