# Generated by Django 5.1.5 on 2025-01-29 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('identifier', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('task_func', models.CharField(choices=[('Testowa analiza - nie robi nic i nie spełnia sygnatury analizy', 'test_task'), ('Analiza rzutów rożnych 1', 'analyse_corners_line_auto'), ('Korelacja posiadania piłki do wyniku meczu', 'correlation_bp2result'), ('Szukanie korelacji pomiędzy statystykami', 'oblicz_korelacje_statystyk_kazdy_z_kazdym')], max_length=128)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.order')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataframe', models.JSONField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.analysis')),
            ],
        ),
    ]
