# Generated by Django 5.1.5 on 2025-01-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasbeer.order'),
        ),
    ]
