# Generated by Django 5.1.5 on 2025-01-30 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0003_alter_job_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'permissions': (('view', 'can_view_analysis'), ('run', 'can_run_analysis')), 'verbose_name_plural': 'analyses'},
        ),
    ]
