# Generated by Django 5.1.5 on 2025-01-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0004_alter_analysis_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='creation datetime'),
        ),
    ]
