# Generated by Django 5.1.5 on 2025-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0005_order_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.AlterField(
            model_name='job',
            name='analysis_name',
            field=models.CharField(choices=[('test_add_analysis_choices', 'Test dodawania analizy'), ('test_task', 'Testowa analiza'), ('analyse_corners_line_auto', 'Analiza rzutów rożnych 1'), ('correlation_bp2result', 'Korelacja posiadania piłki do wyniku meczu'), ('oblicz_korelacje_statystyk_kazdy_z_kazdym', 'Szukanie korelacji pomiędzy statystykami')], max_length=128),
        ),
        migrations.AlterField(
            model_name='match',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
