# Generated by Django 5.1.5 on 2025-02-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0007_alter_analysis_options_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='description',
            field=models.TextField(blank=True, help_text='Left this field empty for auto fill with __doc__ from task function.', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='task_func',
            field=models.CharField(choices=[('test_add_analysis_choices', 'Test dodawania analizy'), ('test_task', 'Testowa analiza'), ('analyse_corners_line_auto', 'Analiza rzutów rożnych 1'), ('corners_box_describe_totals', 'Rzuty rożne describe dla Boxa'), ('analyse_corners_2', 'Analiza rzutów rożnych 2.0'), ('correlation_bp2result', 'Korelacja posiadania piłki do wyniku meczu'), ('oblicz_korelacje_statystyk_kazdy_z_kazdym', 'Szukanie korelacji pomiędzy statystykami')], max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='analysis_name',
            field=models.CharField(choices=[('Test dodawania analizy', 'Test dodawania analizy'), ('Testowa analiza', 'Testowa analiza'), ('Analiza rzutów rożnych 1', 'Analiza rzutów rożnych 1'), ('Rzuty rożne describe dla Boxa', 'Rzuty rożne describe dla Boxa'), ('Analiza rzutów rożnych 2.0', 'Analiza rzutów rożnych 2.0'), ('Korelacja posiadania piłki do wyniku meczu', 'Korelacja posiadania piłki do wyniku meczu'), ('Szukanie korelacji pomiędzy statystykami', 'Szukanie korelacji pomiędzy statystykami')], max_length=128),
        ),
    ]
