# Generated by Django 5.1.5 on 2025-02-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasbeer', '0009_job_error_alter_job_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summary',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
