# Generated by Django 5.1.5 on 2025-02-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kasbeer", "0010_order_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={
                "permissions": [("run_analysis", "Can calculate analysis by job")],
                "verbose_name_plural": "analyses",
            },
        ),
    ]
