"""
Django settings for tutu project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.conf.global_settings import FORM_RENDERER

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('secret_key', None)

#: Load variable from environment file of your own, when no supervisor loaded it
if SECRET_KEY is None:
    environment_file = os.environ['ENV_FILE']
    with open(environment_file, 'r', encoding='utf-8') as configuration:
        lines = configuration.read().splitlines()
        for line in lines:
            if line.startswith('#') or line.startswith(';') or not line.strip():
                #: Skip comments and empty lines
                continue
            try:
                #: Pull out from line and convert to string to eliminate '' or "".
                var, value = list(map(str, line.split('=')))
                # print(f"{var=}, {value=}")
                os.environ[var] = value.strip("'\"")  # here we go.
            except ValueError:
                pass
    SECRET_KEY = os.environ.get('secret_key', None)

# SECURITY WARNING: don't run with debug turned on in production!
#: debug default as False, so PROD will not be affected by accidentially forget set up
debug = os.environ.get('debug', False)
DEBUG = True if debug in ['on', 'true', 'yes', 'y', '1', 'True'] else False

allowed_hosts = '*' if DEBUG else os.environ.get('allowed_hosts', 'localhost 127.0.0.1 [::]')
ALLOWED_HOSTS = allowed_hosts.split(' ')


ALEKSANDER_CONFIG_DIR = os.environ.get('ALEKSANDER_CONFIG_DIR', None)
#: set under another aliased name in environment for Aleksander.
#  os.environ['ALEKSANDER_CONFIG_DIR'] = ALEKSANDER_CONFIG_DIR


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    'warehouse',
    'm2',
    'kasbeer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tutu.urls'

# REST_FRAMEWORK = {
#     # Use Django's standard `django.contrib.auth` permissions,
#     # or allow read-only access for unauthenticated users.
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
#     ]
# }

KASBEER_TEMPLATES = os.path.join(BASE_DIR, 'kasbeer', 'templates')
M2_TEMPLATES = os.path.join(BASE_DIR, 'm2', 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        }
    },
    {
        'BACKEND': 'django.template.backends.jinja2.Jinja2',
        'DIRS': [KASBEER_TEMPLATES, M2_TEMPLATES],
        'APP_DIRS': True,
        'OPTIONS': {
            'environment': 'tutu.jinja2.environment'
        },
    },
]

WSGI_APPLICATION = 'tutu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# db configuration from environment with old default used in testing
# if nothing changed
db_port = os.environ.get('db_port', '43211')
db_user = os.environ.get('db_user', 'postgres')
db_host = os.environ.get('db_host', '127.0.0.1')
db_name = os.environ.get('db_name', 'postgres')
db_password = os.environ.get('db_password', '+ob_Dz+yM;Zl2Uj.W1G5')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'HOST': db_host,
        'PORT': db_port,
        'USER': db_user,
        'PASSWORD': db_password,
        'CONN_MAX_AGE': 10800,  # 3 hours
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# django-guardian
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # default
    'guardian.backends.ObjectPermissionBackend',
)


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = os.environ.get('lang_code', 'en-gb')

TIME_ZONE = os.environ.get('time_zone', 'UTC')

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = os.environ.get('static_url', 'static/')
STATIC_ROOT = os.environ.get('static_root', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = "/"
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
