# Generated by Django 5.1.5 on 2025-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_analysis_id_remove_match_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
